// A conservative allowlist sanitizer for SVG markup generated by the AI
// tutor, before it's ever rendered via dangerouslySetInnerHTML. Strips any
// tag/attribute not on the list — no <script>, no <foreignObject>, no
// <image>/<use> (which could pull in external content), no event-handler
// attributes, no javascript:/data: URLs. Browser-only (DOMParser).
//
// It also drops every node that is neither an element nor text. That is not
// tidiness: the markup is parsed as XML and re-inserted as HTML, and the two
// parsers disagree about those nodes. An XML processing instruction survives
// serialisation verbatim, and the HTML parser then ends it at the first ">",
// releasing whatever follows as real markup:
//
//   <?a ><img src=x onerror=...>?>
//
// which walks straight past an allowlist that only ever inspected elements.
// Verified in Chromium: before this, that payload ran; after it, nothing of it
// is left. (<img> is one of the tags that breaks out of SVG back into HTML,
// which is why it fires at all.)

const ALLOWED_TAGS = new Set([
  "svg", "g", "path", "rect", "circle", "ellipse", "line", "polyline", "polygon",
  "text", "tspan", "defs", "lineargradient", "radialgradient", "stop", "title", "desc",
]);

const ALLOWED_ATTRS = new Set([
  "viewbox", "width", "height", "xmlns", "x", "y", "x1", "y1", "x2", "y2", "cx", "cy", "r", "rx", "ry",
  "points", "d", "fill", "stroke", "stroke-width", "stroke-dasharray", "stroke-linecap", "stroke-linejoin",
  "font-size", "font-family", "font-weight", "text-anchor", "dominant-baseline", "opacity", "fill-opacity",
  "stroke-opacity", "transform", "offset", "stop-color", "stop-opacity", "id", "gradientunits", "gradienttransform",
]);

const MAX_ELEMENTS = 200;

function isSafeValue(value: string): boolean {
  return !/javascript:/i.test(value) && !/^\s*data:/i.test(value);
}

const ELEMENT_NODE = 1;
const TEXT_NODE = 3;

function clean(el: Element): number {
  const tag = el.tagName.toLowerCase();
  if (!ALLOWED_TAGS.has(tag)) {
    el.remove();
    return 0;
  }
  for (const node of Array.from(el.childNodes)) {
    if (node.nodeType !== ELEMENT_NODE && node.nodeType !== TEXT_NODE) {
      node.parentNode?.removeChild(node);
    }
  }
  for (const attr of Array.from(el.attributes)) {
    const name = attr.name.toLowerCase();
    if (!ALLOWED_ATTRS.has(name) || name.startsWith("on") || !isSafeValue(attr.value)) {
      el.removeAttribute(attr.name);
    }
  }
  let count = 1;
  for (const child of Array.from(el.children)) {
    count += clean(child);
  }
  return count;
}

export function sanitizeSvg(raw: string): string | null {
  if (typeof window === "undefined") return null;
  try {
    const doc = new DOMParser().parseFromString(raw, "image/svg+xml");
    if (doc.querySelector("parsererror")) return null;
    const svgEl = doc.querySelector("svg");
    if (!svgEl) return null;

    const elementCount = clean(svgEl);
    if (elementCount === 0 || elementCount > MAX_ELEMENTS) return null;

    if (!svgEl.getAttribute("viewBox") && !svgEl.getAttribute("width")) {
      svgEl.setAttribute("viewBox", "0 0 320 220");
    }
    svgEl.removeAttribute("width");
    svgEl.removeAttribute("height");
    svgEl.setAttribute("class", "h-auto w-full max-w-sm");

    return svgEl.outerHTML;
  } catch {
    return null;
  }
}
